### ISSUE TITLE
sample.pptx won't open in Google Drive

### ISSUE THREAD

**Issue by wilg** [pythonicrubyist/powerpoint#1]
If you upload sample.pptx to Google Drive it will fail and say there was a problem with the upload.

Many of the images do not display in Quick Look for OS X either, or when imported into Keynote.

I think something is wrong with how images are handled.

**Comment by dongyuwei** [comment]
hi, wilg, here is my patch, https://gist.github.com/dongyuwei/66748d22f722145a489c . I tested with Keynote and LibreOffice on OSX 10.10, it just works. The best is that the image is resized properly, not deformed.

**Comment by pythonicrubyist** [comment]
@dongyuwei , if you would like your change to be added to "powerpoint", please feel free to raise a pull request and I will merge it back to the original code. Thanks!
