### ISSUE TITLE
Ability to choose aspect ratio

### ISSUE THREAD

**Issue by arkany** [pythonicrubyist/powerpoint#14]
Hey man, 

This project is awesome, but I was wondering if it would be possible to include an option for selecting a different aspect ratio:

4:3         cx="9144000" cy="6858000" (default)
16:10      cx="9144000" cy="5715000"
16:9        cx="9144000" cy="5143500"

I'll try to figure it out myself, but in the event you've already figured that out, I thought I'd ask ahead of time.

**Comment by pythonicrubyist** [comment]
Thanks @arkany . I added your suggestion to the backlog for the next release. Possibly a couple of of months from now.

**Comment by arkany** [comment]
So sorry to bug, did this ever happen? I couldn't find an update.
