### ISSUE TITLE
Slide contents up to start from the top

### ISSUE THREAD

**Issue by amitrmohanty** [pythonicrubyist/powerpoint#15]
Right now titles are generating from middle of the page. can somebody help..how to start it from top.

**Comment by drg-dhyan** [comment]
I am also facing the same issue. If i use `add_textual_slide` method, title starts from the middle of the slide. Is it something easy to fix? If you could please give any pointers on ways to fix it, that would be great!

Nice work on the gem though!

**Comment by dhyan** [comment]
@amitrmohanty 
I tried resolving the same problem for a text-slide [here](https://github.com/dhyan/powerpoint/tree/customize-text-slide). ie:- when you call something like `deck.add_textual_slide` . Feel free to use that, if that's something what you need  :)

By the way, i can try creating a separate method(may be `deck.add_text_with_content`) and use a different [layout](https://github.com/dhyan/powerpoint/commit/e66524ff27afdb29cb89d43f8a5405321e5e24d9). This call would result in a slide having title from top and other contents separated by bullets. 
@pythonicrubyist ..Thoughts/suggestions please???

**Comment by pythonicrubyist** [comment]
Im working on a major redesign of this gem. The new gem will fix this issue.  hopefully will be released by mid Nov.

**Comment by thaniy** [comment]
Any updates?
