### ISSUE TITLE
Slides with different Templates

### ISSUE THREAD

**Issue by BenjiLewis** [pythonicrubyist/powerpoint#21]
I want to create a Powerpoint with varying templates in the slides. For example, I have two template files - `a.pptx` and `b.pptx`. I want my slide to have the following theme:
```
Slide 1 => Template a
Slide 2 => Template b
Slide 3 => Template b
Slide 4 => Template a
```
I would like to know if this functionality currently exists, or if this is even possible using this Gem?

**Comment by pythonicrubyist** [comment]
@BenjiLewis unfortunately this functionality does not exist. I have added it to the backlog and hopefully will be included in future releases.

**Comment by BenjiLewis** [comment]
Thanks for the repsonse @pythonicrubyist. Looking forward!
