### ISSUE TITLE
Sample.pptx image embed problems

### ISSUE THREAD

**Issue by snkashis** [pythonicrubyist/powerpoint#5]
Running `rake spec` seems to produce a PPTX where only the GIF image shows up while viewing in Keynote & Yosemite Preview.JPG/PNG/SVG do not show up. PNG embeds outside of spec also seems to have issues.

![screen shot 2015-04-23 at 10 41 02 am](https://cloud.githubusercontent.com/assets/361323/7300989/50f9ca02-e9a5-11e4-931d-9bddfecf1a29.png)

**Comment by benjaminwood** [comment]
Seems as though the coordinates parameter is no longer optional... If you add the image location and size, it works!

**Comment by pythonicrubyist** [comment]
This should be fixed now in the latest version.
